package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// sshLogin obtains a short-lived SSH certificate so the user can reach the
// login node.
//
// A dedicated key pair rather than the user's existing one: the certificate is
// cluster-specific and short-lived, and mixing it into id_ed25519 would mean
// every other host sees a shome certificate offered first.
func sshLogin(args []string) error {
	pty := true
	for _, a := range args {
		if a == "--no-pty" {
			pty = false
		}
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	dir := filepath.Join(home, ".ssh")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return err
	}
	keyPath := filepath.Join(dir, "id_shome")

	if _, err := os.Stat(keyPath); err != nil {
		fmt.Println("generating a shome-specific SSH key...")
		cmd := exec.Command("ssh-keygen", "-q", "-t", "ed25519", "-N", "", "-C", "shome", "-f", keyPath)
		cmd.Stderr = os.Stderr
		if err := cmd.Run(); err != nil {
			return fmt.Errorf("ssh-keygen: %w", err)
		}
	}
	pub, err := os.ReadFile(keyPath + ".pub")
	if err != nil {
		return err
	}

	var resp struct {
		Certificate string `json:"certificate"`
		ValidFor    string `json:"valid_for"`
		Principal   string `json:"principal"`
	}
	if err := call("POST", "/sshcert", map[string]any{
		"public_key": string(pub), "pty": pty,
	}, &resp); err != nil {
		return err
	}
	certPath := keyPath + "-cert.pub"
	if err := os.WriteFile(certPath, []byte(resp.Certificate), 0o644); err != nil {
		return err
	}

	fmt.Printf("certificate issued for %s, valid %s\n", resp.Principal, resp.ValidFor)
	fmt.Printf("  key:  %s\n  cert: %s\n\n", keyPath, certPath)

	// Where to ssh to, asked rather than left as a placeholder. The
	// controller knows: it is the machine running the login node and it
	// discovered its own addresses at startup. Printing `<login-host>` and
	// leaving the reader to work it out is the step where this command
	// stopped being usable on its own.
	host, port, why := loginTarget()
	if why != "" {
		fmt.Printf("no login node to connect to: %s\n", why)
		fmt.Printf("The certificate above is still valid once one is running.\n")
		return nil
	}
	fmt.Printf("connect with:\n  ssh -i %s -p %d %s@%s\n\n", keyPath, port, resp.Principal, host)
	fmt.Printf("or add to ~/.ssh/config:\n\n"+
		"  Host shome\n"+
		"    HostName %s\n"+
		"    Port %d\n"+
		"    User %s\n"+
		"    IdentityFile %s\n"+
		"    CertificateFile %s\n\n", host, port, resp.Principal, keyPath, certPath)
	fmt.Printf("then:  ssh shome\n")
	return nil
}

// loginTarget is the address to ssh to, and why there is none if there is
// not.
//
// The first host the controller offers, which is the one it considers most
// likely to be reachable. More are listed by `shome admin login`; which one
// works depends on the network the person is on, and only they know that.
func loginTarget() (host string, port int, why string) {
	li, err := loginState()
	if err != nil {
		return "", 0, err.Error()
	}
	if !li.Enabled {
		if li.Reason != "" {
			return "", 0, li.Reason
		}
		return "", 0, "no login node is running on this cluster"
	}
	port = li.Port
	if port == 0 {
		port = 2222
	}
	if len(li.Hosts) == 0 {
		// Reachable, but the controller could not name itself. localhost is
		// right when the cluster is on this machine, which is the case
		// where this happens.
		return "localhost", port, ""
	}
	return li.Hosts[0], port, ""
}

// sshdConfig prints a ready-to-use sshd configuration for the login node.
func sshdConfig(root string, userCAPub, hostKey, hostCert string) string {
	var b strings.Builder
	w := func(f string, a ...any) { fmt.Fprintf(&b, f+"\n", a...) }
	w("# shome login node -- generated by `shome admin sshd-config`")
	w("#")
	w("# Run as a SEPARATE sshd instance. Do not merge into the system sshd:")
	w("# shome must be removable without having touched your machine's own")
	w("# SSH configuration.")
	w("#")
	w("#   /usr/sbin/sshd -f %s/sshd_config -D", root)
	w("")
	w("Port 2222")
	w("PidFile %s/sshd.pid", root)
	w("")
	w("# Certificates only. No passwords, no authorized_keys, no interactive auth.")
	w("TrustedUserCAKeys %s", userCAPub)
	w("HostKey %s", hostKey)
	w("HostCertificate %s", hostCert)
	w("PubkeyAuthentication yes")
	w("PasswordAuthentication no")
	w("KbdInteractiveAuthentication no")
	w("ChallengeResponseAuthentication no")
	w("AuthenticationMethods publickey")
	w("")
	w("# The principal comes from the verified certificate; shome-shell reads it")
	w("# from the file this exposes. Without it the shell cannot identify users.")
	w("ExposeAuthInfo yes")
	w("")
	w("# Every session runs the restricted dispatcher, whatever the client asks for.")
	w("ForceCommand %s/bin/shome-shell", root)
	w("")
	w("# Each of these would be a way around shome-shell, which is the only")
	w("# boundary between a remote user and this machine's account.")
	w("AllowTcpForwarding no")
	w("AllowStreamLocalForwarding no")
	w("GatewayPorts no")
	w("X11Forwarding no")
	w("PermitTunnel no")
	w("PermitUserRC no")
	w("AllowAgentForwarding no")
	w("Subsystem sftp /bin/false")
	w("PermitRootLogin no")
	w("")
	w("ClientAliveInterval 300")
	w("ClientAliveCountMax 2")
	w("LoginGraceTime 30")
	w("MaxAuthTries 3")
	return b.String()
}
