// Command shome-shell is the login shell for the shome SSH login node.
//
// SECURITY MODEL -- read before changing anything here.
//
// shome does not create OS accounts (doing so on macOS cannot be
// reversed). Every SSH session therefore lands as the SAME OS user: the one
// running sshd. This shell is consequently the ONLY thing standing between a
// remote user and that account's files. It is not a hardened shell, it is not
// a restricted shell in the rbash sense -- it is a fixed command dispatcher
// that never invokes a shell, never expands globs, and never execs anything
// but itself.
//
// Concretely, it must never:
//   - pass user input to /bin/sh, exec.Command with a shell, or any interpreter
//   - accept a command outside the allow-list below
//   - read files by a user-supplied path
//
// The sshd config generated by `shome admin sshd-config` additionally disables
// pty allocation, port/agent/X11 forwarding, and SFTP -- each of which would
// otherwise be a way around this dispatcher.
package main

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/davidwu/shome/internal/sshca"
)

// allowed is the complete set of verbs a remote user may run. Anything not
// listed is refused; there is no escape hatch and no pass-through.
var allowed = map[string]bool{
	"sbatch": true, "squeue": true, "scancel": true, "sinfo": true,
	"sacct": true, "scontrol": true, "cat": true, "fetch": true,
	"storage": true, "whoami": true, "events": true, "help": true,
}

func main() {
	principal := sshPrincipal()
	if principal == "" {
		fmt.Fprintln(os.Stderr, "shome: could not determine your identity from the SSH certificate")
		fmt.Fprintln(os.Stderr, "  (the login node needs 'ExposeAuthInfo yes' in its sshd_config)")
		os.Exit(1)
	}

	// A forced command: ssh cluster "squeue -u me"
	if cmd := os.Getenv("SSH_ORIGINAL_COMMAND"); cmd != "" {
		os.Exit(runLine(principal, cmd))
	}
	// Interactive session.
	fmt.Printf("shome login node -- you are %s\n", principal)
	fmt.Println("type 'help' for commands, 'exit' to leave")
	sc := bufio.NewScanner(os.Stdin)
	for {
		fmt.Printf("%s@shome$ ", principal)
		if !sc.Scan() {
			fmt.Println()
			return
		}
		line := strings.TrimSpace(sc.Text())
		switch line {
		case "":
			continue
		case "exit", "quit", "logout":
			return
		}
		runLine(principal, line)
	}
}

// runLine parses and dispatches one command line.
func runLine(principal, line string) int {
	fields, err := splitArgs(line)
	if err != nil {
		fmt.Fprintln(os.Stderr, "shome:", err)
		return 1
	}
	if len(fields) == 0 {
		return 0
	}
	verb := fields[0]
	if !allowed[verb] {
		fmt.Fprintf(os.Stderr, "shome: %q is not available here.\navailable: %s\n",
			verb, strings.Join(allowedList(), " "))
		return 1
	}

	self, err := os.Executable()
	if err != nil {
		fmt.Fprintln(os.Stderr, "shome:", err)
		return 1
	}
	shomeBin := filepath.Join(filepath.Dir(self), "shome")
	if _, err := os.Stat(shomeBin); err != nil {
		fmt.Fprintln(os.Stderr, "shome: the shome CLI is not installed next to shome-shell")
		return 1
	}

	// exec.Command with an explicit argv -- never a shell string, so no
	// metacharacter in the user's input can start a second process.
	c := exec.Command(shomeBin, fields...)
	c.Stdin, c.Stdout, c.Stderr = os.Stdin, os.Stdout, os.Stderr
	env := append(os.Environ(), "SHOME_ACT_AS="+principal)
	// An sshd session gets a minimal environment, so SHOME_ROOT is usually
	// absent and the CLI would look in the wrong place for the socket and the
	// admin token. shome-shell is installed at <root>/bin/shome-shell, so it
	// can recover the root from its own location.
	if os.Getenv("SHOME_ROOT") == "" {
		env = append(env, "SHOME_ROOT="+filepath.Dir(filepath.Dir(self)))
	}
	c.Env = env
	if err := c.Run(); err != nil {
		if ee, ok := err.(*exec.ExitError); ok {
			return ee.ExitCode()
		}
		fmt.Fprintln(os.Stderr, "shome:", err)
		return 1
	}
	return 0
}

func allowedList() []string {
	out := make([]string, 0, len(allowed))
	for k := range allowed {
		out = append(out, k)
	}
	return out
}

// splitArgs splits a command line on whitespace, honouring simple quoting.
//
// Deliberately minimal: no globbing, no variable expansion, no command
// substitution, no operators. A user's quotes group arguments and nothing more.
func splitArgs(line string) ([]string, error) {
	var out []string
	var cur strings.Builder
	var quote rune
	started := false
	for _, r := range line {
		switch {
		case quote != 0:
			if r == quote {
				quote = 0
			} else {
				cur.WriteRune(r)
			}
		case r == '\'' || r == '"':
			quote = r
			started = true
		case r == ' ' || r == '\t':
			if started || cur.Len() > 0 {
				out = append(out, cur.String())
				cur.Reset()
				started = false
			}
		// Reject shell metacharacters outright rather than trying to escape
		// them. Nothing downstream interprets them, but refusing makes the
		// intent explicit and fails loudly if that ever changes.
		case strings.ContainsRune("|&;<>$`(){}[]*?!\\\n", r):
			return nil, fmt.Errorf("character %q is not allowed in commands here", string(r))
		default:
			cur.WriteRune(r)
		}
	}
	if quote != 0 {
		return nil, fmt.Errorf("unclosed quote")
	}
	if started || cur.Len() > 0 {
		out = append(out, cur.String())
	}
	return out, nil
}

// sshPrincipal extracts the certificate principal sshd authenticated.
//
// The identity lives in the certificate's KeyId, inside the base64 blob that
// sshd writes when ExposeAuthInfo is enabled -- not as plain text on the line.
// It is trustworthy because sshd verified the certificate's signature and
// validity before writing it; nothing here comes from the client.
func sshPrincipal() string {
	path := os.Getenv("SSH_USER_AUTH")
	if path == "" {
		return ""
	}
	b, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	name, err := sshca.PrincipalFromAuthInfo(b)
	if err != nil {
		return ""
	}
	return name
}
